### ISSUE TITLE
Script does not work

### ISSUE THREAD

**Issue by ianlockhead** [007revad/Synology_ContainerManager_IPv6#3]
Hi, the script does not work for me. After running the script Synology can't boot the DSM package and Container Manager needs to be repaired. Fixed cidr was unchanged while I am using the fe80::1/64 as well. Thanks for help

**Comment by 007revad** [comment]
What do the following 2 commands return?
```
cat "/var/packages/ContainerManager/etc/dockerd.json"
cat "/var/packages/ContainerManager/target/config/dockerd.json"
```

**Comment by yuri609** [comment]
`ianlockhead@Synology:/$ sudo jq . "/var/packages/ContainerManager/etc/dockerd.json"
Password: 
{
  "data-root": "/var/packages/ContainerManager/var/docker",
  "log-driver": "db",
  "registry-mirrors": [],
  "seccomp-profile": "unconfined",
  "storage-driver": "btrfs"
}
ianlockhead@Synology:/$ sudo jq . "/var/packages/ContainerManager/target/config/dockerd.json"
{
  "registry-mirrors": [],
  "data-root": "/var/packages/ContainerManager/var/docker",
  "log-driver": "db",
  "seccomp-profile": "unconfined"`

**Comment by yuri609** [comment]
ianlockhead@Synology:/$ sudo jq . "/var/packages/ContainerManager/etc/dockerd.json"
{
  "data-root": "/var/packages/ContainerManager/var/docker",
  "log-driver": "db",
  "registry-mirrors": [],
  "seccomp-profile": "unconfined",
  "storage-driver": "btrfs"
}
ianlockhead@Synology:/$ sudo jq . "/var/packages/ContainerManager/target/config/dockerd.json"
{
  "registry-mirrors": [],
  "data-root": "/var/packages/ContainerManager/var/docker",
  "log-driver": "db",
  "seccomp-profile": "unconfined"

**Comment by 007revad** [comment]
Was this after clicking on Repair in storage manager?

What do these commands return?
```
cat "/var/packages/ContainerManager/etc/dockerd.json" && echo
cat "/var/packages/ContainerManager/target/config/dockerd.json" && echo
```

**Comment by ianlockhead** [comment]
Hi, yes both json files were restored manually from backup after repairing the syno package.
I can run the script again and paste the cat command output but it will brick the package again I think.

After backup restore the jsons looks:

ianlockhead@Synology:/$ sudo cat "/var/packages/ContainerManager/etc/dockerd.json" && echo
Password: 
{"data-root":"/var/packages/ContainerManager/var/docker","log-driver":"db","registry-mirrors":[],"seccomp-profile":"unconfined","storage-driver":"btrfs"}
ianlockhead@Synology:/$ sudo cat "/var/packages/ContainerManager/target/config/dockerd.json" && echo
{
	"registry-mirrors": [],
	"data-root": "/var/packages/ContainerManager/var/docker",
	"log-driver": "db",
	"seccomp-profile": "unconfined"
}

Thanks

**Comment by 007revad** [comment]
I've been working on a new, much improved, version of the script that uses jq to add the ipv6 key/value pairs to the json files. This will prevent changing any existing custom settings in the json files.

But at the moment it sometimes results in an empty /var/packages/ContainerManager/target/config/dockerd.json

**Comment by 007revad** [comment]
Do you want to try the new v2.0.4

**Comment by ianlockhead** [comment]
@007revad The new script 2.0.4 is working like a charm! B-) I have now IPv6 enabled. Thank you so much!!!
Last question.. did you resolve how to support IPv6 on host network driver?
![Snímek obrazovky 2024-07-11 v 11 15 28](https://github.com/007revad/Synology_ContainerManager_IPv6/assets/8457404/cd55ad5e-0164-474b-b306-60d6f006fe7f)

**Comment by 007revad** [comment]
Excellent.

From this https://docs.docker.com/config/daemon/ipv6/ webpage it looks like you can only enable IPv6 on the bridge network, or create a new IPv6 network via docker compose.
